#!/usr/bin/env node
// @generated-artifact tracked-output
//
// Render the nightly routine's open items as a TRACKED markdown inbox the owner
// answers by ticking a checkbox.
//
// WHY MARKDOWN AND NOT THE HTML DIGEST IT REPLACED. The digest was a static
// file:// page plus a localhost server, because a file:// page cannot persist a
// click. Everything about that was technically correct and it still made
// answering a chore: you had to be at the machine, remember a command, and have
// the server running. The requirement was never buttons — it was a clear, easy,
// ASYNC way to answer a proposition and have an agent act on it. A tracked
// markdown file is exactly that: any editor opens it, GitHub's web UI edits it
// from a phone, git syncs it between machines, and it needs no process at all.
//
// The file is REGENERATED, never hand-maintained: answered items drop out on the
// next render. Its durable half is `.claude/nightly-decisions.json` — the inbox
// is the input surface, the ledger is the record. One home per fact.
//
// Usage:
//   node scripts/nightly/render-inbox.mjs [--root <repo>] [--check]
//
// ARGV IS REFUSED, NOT IGNORED — writing the queue is the default action, so a
// query-shaped flag must never perform it (see `scripts/shared/argvGuard.mjs`).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import {
  readOpenItems,
  readDecisions,
  partitionBySettled,
  answeredNotDone,
  renderQueueIndex,
  LEGS,
  LEG_TITLES,
  INBOX_RELPATH,
  OPEN_ITEMS_RELPATH,
  OPEN_ITEMS_INDEX_RELPATH,
  DECISIONS_RELPATH,
} from './items.mjs';
import { guardArgv } from '../shared/argvGuard.mjs';

const USAGE = 'node scripts/nightly/render-inbox.mjs [--root <repo>] [--check]';

const MARKER = 'nightly:item';

/** The machine-readable anchor that ties a rendered block back to its subject. */
export const itemMarker = (key) => `<!-- ${MARKER} key=${key} -->`;

/** Match a rendered item block's anchor. Kept next to the writer so the two cannot drift. */
export const MARKER_RE = new RegExp(`<!--\\s*${MARKER}\\s+key=([0-9a-f]+)\\s*-->`, 'g');

// ── citation exemption for quoted item content ───────────────────────────────
// Item prose quotes a code path precisely BECAUSE it is stale ("`src/x.ts` was
// deleted") — that is the finding, not a citation, so the doc-citation gate
// (`scripts/check-doc-code-citations.mjs`) has to be told. A hand-placed marker
// cannot survive here: this file is whole-file generated, so the next render
// deletes it and the gate goes red on the same quoted paths again. The GENERATOR
// therefore emits the exemption, which makes it as durable as the content it
// covers.
//
// Placement is the narrowest the gate honours: it exempts per LINE, same-line or
// line-above, and only lines carrying item-sourced content are marked — prose
// this renderer authors stays checked. Same-line rather than line-above because a
// comment on its own line is an HTML block: inserted into a soft-wrapped
// paragraph it would split the paragraph in two.
const EXEMPT_PATTERN = String.raw`<!--\s*doc-citation-exempt:.*?-->`;

/** The exemption in the one grammar the gate honours. */
const CITATION_EXEMPT = '<!-- doc-citation-exempt: quoted item prose, not citations -->';

/** Reader half of the same grammar — one home, so a consumer cannot drift from the writer. */
export const CITATION_EXEMPT_RE = new RegExp(`\\s*${EXEMPT_PATTERN}`, 'g');

const HAS_CITATION_EXEMPT = new RegExp(EXEMPT_PATTERN);

/**
 * Mark ITEM-SOURCED text — anything interpolated from `open-items.json` or the
 * decisions ledger — as exempt from citation resolution. Only physical lines that
 * actually carry a backticked token are marked (the gate's citation unit), and an
 * already-marked line is left alone.
 */
function exemptQuoted(text) {
  return String(text ?? '')
    .split('\n')
    .map((line) =>
      line.includes('`') && !HAS_CITATION_EXEMPT.test(line) ? `${line} ${CITATION_EXEMPT}` : line,
    )
    .join('\n');
}

const PREAMBLE = `# Nightly decisions inbox

> **GENERATED by \`node scripts/nightly/render-inbox.mjs\`.** Everything except your
> answers is rewritten on each nightly run — answered items drop out on their own.
> Your answers are the one part that is read back, so edit freely inside the answer
> blocks and nowhere else.

## How to answer

For each proposition below, **tick exactly one box** by putting an \`x\` in it —
\`- [x]\` — and save the file. That is the whole workflow. Any editor works, and so
does GitHub's web editor if you are away from the machine.

- Ticking one of the numbered options records that option's answer verbatim.
- **Other** records whatever you write in the *Notes* block instead.
- **Won't fix** settles it as not-doing; write why in *Notes*.
- **Ask back** is for when the proposition is wrong or under-specified — the item
  stays open and your note comes back to the next run.

The last three require a note; the numbered options do not. Then, next time an agent
starts here, it applies your answers (\`node scripts/nightly/ingest-answers.mjs\`),
records them in the tracked ledger, and does the work.
`;

const esc = (s) => String(s ?? '').replace(/\r/g, '');

/**
 * An item the owner asked BACK on: show their question and the reply, above the
 * fresh answer boxes. Without this the item returns looking untouched, which
 * reads as the routine ignoring them.
 */
function renderExchange(decision) {
  if (!decision || decision.disposition !== 'question') return [];
  const lines = ['### ⤺ You asked back', ''];
  for (const l of esc(decision.answer).split('\n')) lines.push(exemptQuoted(`> ${l}`));
  lines.push('');
  if (decision.reply) {
    lines.push('**Answer:**', '', exemptQuoted(esc(decision.reply)), '');
  } else {
    lines.push('*(Not answered yet — the next agent to run the routine owes you a reply here.)*', '');
  }
  return lines;
}

function renderItem(item, decision) {
  const opts = Array.isArray(item.options) ? item.options : [];
  const nights = Number(item.nights_open) || 0;
  const age = nights >= 5 ? ` · **open ${nights} nights**` : nights > 0 ? ` · open ${nights} night${nights === 1 ? '' : 's'}` : '';

  const lines = [];
  lines.push(itemMarker(item.subject_key));
  lines.push('');
  lines.push(exemptQuoted(`## \`${item.id}\` — ${esc(item.title)}`));
  lines.push('');
  lines.push(exemptQuoted(`*${LEG_TITLES[item.leg] ?? item.leg}${age} · \`${esc(item.path)}\`*`));
  lines.push('');

  if (item.eli5) {
    lines.push('### In plain terms');
    lines.push('');
    lines.push(exemptQuoted(esc(item.eli5)));
    lines.push('');
  }

  lines.push('### The question');
  lines.push('');
  lines.push(exemptQuoted(esc(item.question)));
  lines.push('');
  lines.push(...renderExchange(decision));
  lines.push('### Your answer');
  lines.push('');
  opts.forEach((o, i) => {
    lines.push(exemptQuoted(`- [ ] **${i + 1}. ${esc(o.label)}** — ${esc(o.answer)}`));
  });
  lines.push(`- [ ] **Other** — record what I write in Notes below.`);
  lines.push(`- [ ] **Won't fix** — not doing this; reason in Notes.`);
  lines.push(`- [ ] **Ask back** — the proposition is wrong or unclear; question in Notes, item stays open.`);
  lines.push('');
  lines.push('```notes');
  lines.push('');
  lines.push('```');
  lines.push('');

  if (item.patch_path) {
    lines.push(exemptQuoted(`Full proposal: [\`${item.patch_path}\`](../${item.patch_path})`));
    lines.push('');
  }

  const ev = Array.isArray(item.evidence) ? item.evidence : [];
  if (ev.length > 0) {
    lines.push('<details>');
    lines.push(`<summary>Evidence (${ev.length}) — what was verified against code, and how</summary>`);
    lines.push('');
    for (const e of ev) lines.push(exemptQuoted(`- ${esc(e)}`));
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  return lines.join('\n');
}

/** @param {{items: any[], decisions?: any, run?: {date?: string, head?: string}|null, applied?: any[], skipped?: any[]}} options */
export function renderInbox({ items, decisions = {}, run = null, applied = [], skipped = [] }) {
  const out = [PREAMBLE];

  if (run) {
    out.push(`\n*Last run: ${run.date ?? 'unknown'}${run.head ? ` at \`${run.head}\`` : ''}.*\n`);
  }

  // `grandfathered` is deliberately NOT surfaced: those subjects predate
  // completion tracking, so their landing state is unknown by construction and
  // reporting ~50 of them as outstanding would be a false RED — which trains the
  // reader to skip the whole file, exactly like the false GREEN it replaced.
  const { actionable } = answeredNotDone(decisions);
  if (actionable.length > 0) {
    out.push(
      `\n> **${actionable.length} answered item${actionable.length === 1 ? '' : 's'} not yet marked done.** ` +
        `An answer records your reply; it does not claim the work exists. ` +
        `Run \`node scripts/nightly/answer.mjs --list\` to see them.\n`,
    );
  }

  if (items.length === 0) {
    out.push('\n---\n\n## Nothing to answer\n\nNo open propositions. The next run will refill this file if it finds any.\n');
  } else {
    out.push('\n---\n');
    for (const leg of LEGS) {
      const group = items.filter((i) => i.leg === leg);
      if (group.length === 0) continue;
      out.push(`\n# ${LEG_TITLES[leg] ?? leg}\n`);
      for (const item of group) out.push(`\n${renderItem(item, decisions[item.subject_key])}\n`);
    }
    const ungrouped = items.filter((i) => !LEGS.includes(i.leg));
    for (const item of ungrouped) out.push(`\n${renderItem(item, decisions[item.subject_key])}\n`);
  }

  if (applied.length > 0) {
    out.push('\n<details>\n<summary>What the last run changed on its own</summary>\n');
    for (const a of applied) out.push(exemptQuoted(`\n- ${esc(a)}`));
    out.push('\n\n</details>\n');
  }
  if (skipped.length > 0) {
    out.push('\n<details>\n<summary>What the last run could NOT cover</summary>\n');
    for (const s of skipped) out.push(exemptQuoted(`\n- ${esc(s)}`));
    out.push('\n\n</details>\n');
  }

  return out.join('\n').replace(/\n{4,}/g, '\n\n\n').trimEnd() + '\n';
}

export function projectInbox(root) {
  const state = readOpenItems(root);
  const decisions = readDecisions(root);
  const { open } = partitionBySettled(state.items, decisions, root);
  const body = renderInbox({
    items: open,
    decisions,
    run: state.run,
    applied: state.applied ?? [],
    skipped: state.skipped ?? [],
  });
  const snapshot = JSON.stringify({ ...state, items: open }, null, 2) + '\n';
  const index = renderQueueIndex({ items: open, run: state.run });
  return { body, snapshot, index, open: open.length };
}

export function writeInbox(root) {
  const { body, snapshot, index, open } = projectInbox(root);
  const snapshotPath = join(root, OPEN_ITEMS_RELPATH);
  const indexPath = join(root, OPEN_ITEMS_INDEX_RELPATH);
  const out = join(root, INBOX_RELPATH);
  mkdirSync(dirname(snapshotPath), { recursive: true });
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(snapshotPath, snapshot, 'utf8');
  writeFileSync(indexPath, index, 'utf8');
  writeFileSync(out, body, 'utf8');
  return { path: out, open };
}

/**
 * Read-only parity arm for the tracked inbox projection.
 *
 * Both tracked artifacts are DERIVED — the markdown render and the persisted
 * queue are projections of `open-items.json` folded through
 * `.claude/nightly-decisions.json`. This arm re-derives both and name-compares
 * them, so neither can keep asserting an item is open once the ledger records
 * it done. That is the whole point: on 2026-08-27 the queue and the snapshot
 * still presented six settled propositions as open, and a lap read four of them
 * and put them back to the owner — one answer would have REVERTED a completed
 * decision. Nothing reconciled the three artifacts then; this is the arm that
 * does, and `check:nightly-inbox` plus its pre-commit leg are where it runs.
 *
 * A ledger that cannot be read is a REFUSAL, not a stale render: it lands the
 * same non-zero verdict but names itself, instead of surfacing as an uncaught
 * parse error from inside the projection.
 */
function readIfPresent(file) {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return null; // missing is stale; the write arm owns creation
  }
}

export function checkInbox(root) {
  const out = join(root, INBOX_RELPATH);
  const snapshotPath = join(root, OPEN_ITEMS_RELPATH);
  const indexPath = join(root, OPEN_ITEMS_INDEX_RELPATH);
  let projection;
  try {
    projection = projectInbox(root);
  } catch (err) {
    return {
      path: out,
      snapshotPath,
      indexPath,
      open: 0,
      fresh: false,
      stale: [DECISIONS_RELPATH],
      reason:
        `${DECISIONS_RELPATH} could not be read, so the queue cannot be reconciled against it: ` +
        `${err instanceof Error ? err.message : String(err)}`,
    };
  }
  const { body, snapshot, index, open } = projection;

  const stale = [];
  if (readIfPresent(out) !== body) stale.push(INBOX_RELPATH);
  if (readIfPresent(snapshotPath) !== snapshot) stale.push(OPEN_ITEMS_RELPATH);
  if (readIfPresent(indexPath) !== index) stale.push(OPEN_ITEMS_INDEX_RELPATH);
  return {
    path: out,
    snapshotPath,
    indexPath,
    open,
    fresh: stale.length === 0,
    stale,
    reason:
      stale.length === 0
        ? null
        : `${stale.join(' and ')} no longer match the queue projected through ` +
          `${DECISIONS_RELPATH} — the ledger settles an item that the tracked artifact still ` +
          `asserts open, or an item's premise has gone from the tree.`,
  };
}

if (process.argv[1] && process.argv[1].endsWith('render-inbox.mjs')) {
  const parsed = guardArgv(process.argv.slice(2), {
    name: 'render-inbox',
    usage: USAGE,
    values: ['--root'],
    flags: ['--check'],
  });
  const rootArg = parsed.get('--root');
  const root = rootArg ?? (process.env.CLAUDE_PROJECT_DIR || process.cwd());
  if (parsed.has('--check')) {
    const result = checkInbox(root);
    if (!result.fresh) {
      console.error(
        `${result.stale.join(' and ')} stale or missing.\n` +
          `${result.reason ? `${result.reason}\n` : ''}` +
          `Fix: node scripts/nightly/render-inbox.mjs${rootArg ? ` --root ${rootArg}` : ''}`,
      );
      process.exit(1);
    }
    console.log(`✓ nightly inbox: ${result.open} open item(s), tracked render is current`);
    process.exit(0);
  }
  const { open } = writeInbox(root);
  console.log(`nightly inbox: ${open} open item(s) → ${INBOX_RELPATH}`);
}
