#!/usr/bin/env node
//
// Render the nightly routine's open items as a TRACKED markdown inbox the owner
// answers by ticking a checkbox.
//
// WHY MARKDOWN AND NOT THE HTML DIGEST IT REPLACED. The digest was a static
// file:// page plus a localhost server, because a file:// page cannot persist a
// click. Everything about that was technically correct and it still made
// answering a chore: you had to be at the machine, remember a command, and have
// the server running. The requirement was never buttons — it was a clear, easy,
// ASYNC way to answer a proposition and have an agent act on it. A tracked
// markdown file is exactly that: any editor opens it, GitHub's web UI edits it
// from a phone, git syncs it between machines, and it needs no process at all.
//
// The file is REGENERATED, never hand-maintained: answered items drop out on the
// next render. Its durable half is `.claude/nightly-decisions.json` — the inbox
// is the input surface, the ledger is the record. One home per fact.
//
// Usage:
//   node scripts/nightly/render-inbox.mjs [--root <repo>]
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { readOpenItems, readDecisions, partitionBySettled, answeredNotDone, LEGS, LEG_TITLES, INBOX_RELPATH } from './items.mjs';

const MARKER = 'nightly:item';

/** The machine-readable anchor that ties a rendered block back to its subject. */
export const itemMarker = (key) => `<!-- ${MARKER} key=${key} -->`;

/** Match a rendered item block's anchor. Kept next to the writer so the two cannot drift. */
export const MARKER_RE = new RegExp(`<!--\\s*${MARKER}\\s+key=([0-9a-f]+)\\s*-->`, 'g');

const PREAMBLE = `# Nightly decisions inbox

> **GENERATED by \`node scripts/nightly/render-inbox.mjs\`.** Everything except your
> answers is rewritten on each nightly run — answered items drop out on their own.
> Your answers are the one part that is read back, so edit freely inside the answer
> blocks and nowhere else.

## How to answer

For each proposition below, **tick exactly one box** by putting an \`x\` in it —
\`- [x]\` — and save the file. That is the whole workflow. Any editor works, and so
does GitHub's web editor if you are away from the machine.

- Ticking one of the numbered options records that option's answer verbatim.
- **Other** records whatever you write in the *Notes* block instead.
- **Won't fix** settles it as not-doing; write why in *Notes*.
- **Ask back** is for when the proposition is wrong or under-specified — the item
  stays open and your note comes back to the next run.

The last three require a note; the numbered options do not. Then, next time an agent
starts here, it applies your answers (\`node scripts/nightly/ingest-answers.mjs\`),
records them in the tracked ledger, and does the work.
`;

const esc = (s) => String(s ?? '').replace(/\r/g, '');

/**
 * An item the owner asked BACK on: show their question and the reply, above the
 * fresh answer boxes. Without this the item returns looking untouched, which
 * reads as the routine ignoring them.
 */
function renderExchange(decision) {
  if (!decision || decision.disposition !== 'question') return [];
  const lines = ['### ⤺ You asked back', ''];
  for (const l of esc(decision.answer).split('\n')) lines.push(`> ${l}`);
  lines.push('');
  if (decision.reply) {
    lines.push('**Answer:**', '', esc(decision.reply), '');
  } else {
    lines.push('*(Not answered yet — the next agent to run the routine owes you a reply here.)*', '');
  }
  return lines;
}

function renderItem(item, decision) {
  const opts = Array.isArray(item.options) ? item.options : [];
  const nights = Number(item.nights_open) || 0;
  const age = nights >= 5 ? ` · **open ${nights} nights**` : nights > 0 ? ` · open ${nights} night${nights === 1 ? '' : 's'}` : '';

  const lines = [];
  lines.push(itemMarker(item.subject_key));
  lines.push('');
  lines.push(`## \`${item.id}\` — ${esc(item.title)}`);
  lines.push('');
  lines.push(`*${LEG_TITLES[item.leg] ?? item.leg}${age} · \`${esc(item.path)}\`*`);
  lines.push('');

  if (item.eli5) {
    lines.push('### In plain terms');
    lines.push('');
    lines.push(esc(item.eli5));
    lines.push('');
  }

  lines.push('### The question');
  lines.push('');
  lines.push(esc(item.question));
  lines.push('');
  lines.push(...renderExchange(decision));
  lines.push('### Your answer');
  lines.push('');
  opts.forEach((o, i) => {
    lines.push(`- [ ] **${i + 1}. ${esc(o.label)}** — ${esc(o.answer)}`);
  });
  lines.push(`- [ ] **Other** — record what I write in Notes below.`);
  lines.push(`- [ ] **Won't fix** — not doing this; reason in Notes.`);
  lines.push(`- [ ] **Ask back** — the proposition is wrong or unclear; question in Notes, item stays open.`);
  lines.push('');
  lines.push('```notes');
  lines.push('');
  lines.push('```');
  lines.push('');

  if (item.patch_path) {
    lines.push(`Full proposal: [\`${item.patch_path}\`](../${item.patch_path})`);
    lines.push('');
  }

  const ev = Array.isArray(item.evidence) ? item.evidence : [];
  if (ev.length > 0) {
    lines.push('<details>');
    lines.push(`<summary>Evidence (${ev.length}) — what was verified against code, and how</summary>`);
    lines.push('');
    for (const e of ev) lines.push(`- ${esc(e)}`);
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  return lines.join('\n');
}

export function renderInbox({ items, decisions = {}, run = null, applied = [], skipped = [] }) {
  const out = [PREAMBLE];

  if (run) {
    out.push(`\n*Last run: ${run.date ?? 'unknown'}${run.head ? ` at \`${run.head}\`` : ''}.*\n`);
  }

  // `grandfathered` is deliberately NOT surfaced: those subjects predate
  // completion tracking, so their landing state is unknown by construction and
  // reporting ~50 of them as outstanding would be a false RED — which trains the
  // reader to skip the whole file, exactly like the false GREEN it replaced.
  const { actionable } = answeredNotDone(decisions);
  if (actionable.length > 0) {
    out.push(
      `\n> **${actionable.length} answered item${actionable.length === 1 ? '' : 's'} not yet marked done.** ` +
        `An answer records your reply; it does not claim the work exists. ` +
        `Run \`node scripts/nightly/answer.mjs --list\` to see them.\n`,
    );
  }

  if (items.length === 0) {
    out.push('\n---\n\n## Nothing to answer\n\nNo open propositions. The next run will refill this file if it finds any.\n');
  } else {
    out.push('\n---\n');
    for (const leg of LEGS) {
      const group = items.filter((i) => i.leg === leg);
      if (group.length === 0) continue;
      out.push(`\n# ${LEG_TITLES[leg] ?? leg}\n`);
      for (const item of group) out.push(`\n${renderItem(item, decisions[item.subject_key])}\n`);
    }
    const ungrouped = items.filter((i) => !LEGS.includes(i.leg));
    for (const item of ungrouped) out.push(`\n${renderItem(item, decisions[item.subject_key])}\n`);
  }

  if (applied.length > 0) {
    out.push('\n<details>\n<summary>What the last run changed on its own</summary>\n');
    for (const a of applied) out.push(`\n- ${esc(a)}`);
    out.push('\n\n</details>\n');
  }
  if (skipped.length > 0) {
    out.push('\n<details>\n<summary>What the last run could NOT cover</summary>\n');
    for (const s of skipped) out.push(`\n- ${esc(s)}`);
    out.push('\n\n</details>\n');
  }

  return out.join('\n').replace(/\n{4,}/g, '\n\n\n').trimEnd() + '\n';
}

export function writeInbox(root) {
  const state = readOpenItems(root);
  const decisions = readDecisions(root);
  const { open } = partitionBySettled(state.items, decisions, root);
  const body = renderInbox({
    items: open,
    decisions,
    run: state.run,
    applied: state.applied ?? [],
    skipped: state.skipped ?? [],
  });
  const out = join(root, INBOX_RELPATH);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, body, 'utf8');
  return { path: out, open: open.length };
}

if (process.argv[1] && process.argv[1].endsWith('render-inbox.mjs')) {
  const args = process.argv.slice(2);
  const rootIdx = args.indexOf('--root');
  const root = rootIdx >= 0 ? args[rootIdx + 1] : process.env.CLAUDE_PROJECT_DIR || process.cwd();
  const { open } = writeInbox(root);
  console.log(`nightly inbox: ${open} open item(s) → ${INBOX_RELPATH}`);
}
