import type { RepoManifest } from "../types.js";
import { normalizeExtractorPath } from "./pathPatterns.js";

export interface InventoryInputFile {
  path: string;
  size_bytes: number;
  hash?: string;
}

// --- AUTO-GENERATED LANGUAGE MAP START ---
const LANGUAGE_BY_EXTENSION: Record<string, string> = {
  "1": "roff",
  "2": "roff",
  "3": "roff",
  "4": "roff",
  "5": "roff",
  "6": "roff",
  "7": "roff",
  "8": "roff",
  "9": "roff",
  "bsl": "1c enterprise",
  "os": "1c enterprise",
  "2da": "2-dimensional array",
  "4dm": "4d",
  "abap": "abap",
  "asddls": "abap cds",
  "abnf": "abnf",
  "asc": "ags script",
  "ash": "ags script",
  "aidl": "aidl",
  "al": "al",
  "alg": "algol",
  "ampl": "ampl",
  "mod": "ampl",
  "g4": "antlr",
  "apib": "api blueprint",
  "apl": "apl",
  "dyalog": "apl",
  "asl": "asl",
  "dsl": "asl",
  "asn": "asn.1",
  "asn1": "asn.1",
  "asax": "asp.net",
  "ascx": "asp.net",
  "ashx": "asp.net",
  "asmx": "asp.net",
  "aspx": "asp.net",
  "axd": "asp.net",
  "dats": "ats",
  "hats": "ats",
  "sats": "ats",
  "as": "actionscript",
  "adb": "ada",
  "ada": "ada",
  "ads": "ada",
  "txt": "text",
  "afm": "adobe font metrics",
  "agda": "agda",
  "ak": "aiken",
  "als": "alloy",
  "OutJob": "altium designer",
  "PcbDoc": "altium designer",
  "PrjPCB": "altium designer",
  "SchDoc": "altium designer",
  "angelscript": "angelscript",
  "lp": "answer set programming",
  "antlers.html": "antlers",
  "antlers.php": "antlers",
  "antlers.xml": "antlers",
  "apacheconf": "apacheconf",
  "vhost": "apacheconf",
  "cls": "apex",
  "apex": "apex",
  "trigger": "apex",
  "agc": "apollo guidance computer",
  "applescript": "applescript",
  "scpt": "applescript",
  "arc": "arc",
  "asciidoc": "asciidoc",
  "adoc": "asciidoc",
  "aj": "aspectj",
  "asm": "assembly",
  "a51": "assembly",
  "i": "assembly",
  "inc": "assembly",
  "nas": "assembly",
  "nasm": "assembly",
  "s": "assembly",
  "astro": "astro",
  "asy": "asymptote",
  "aug": "augeas",
  "ahk": "autohotkey",
  "ahkl": "autohotkey",
  "au3": "autoit",
  "avdl": "avro idl",
  "awk": "awk",
  "auk": "awk",
  "gawk": "awk",
  "mawk": "awk",
  "nawk": "awk",
  "mch": "b (formal method)",
  "bas": "b4x",
  "bqn": "bqn",
  "bal": "ballerina",
  "bat": "batchfile",
  "cmd": "batchfile",
  "bf": "beef",
  "befunge": "befunge",
  "be": "berry",
  "bib": "bibtex",
  "bibtex": "bibtex",
  "bst": "bibtex style",
  "bicep": "bicep",
  "bicepparam": "bicep",
  "bs": "bluespec bh",
  "bison": "bison",
  "bb": "bitbake",
  "bbappend": "bitbake",
  "bbclass": "bitbake",
  "blade": "blade",
  "blade.php": "blade",
  "decls": "blitzbasic",
  "bmx": "blitzmax",
  "bsv": "bluespec",
  "boo": "boo",
  "bpl": "boogie",
  "b": "brainfuck",
  "brs": "brightscript",
  "bru": "bru",
  "c": "c",
  "cats": "c",
  "h": "c",
  "h.in": "c",
  "idc": "c",
  "cs": "c#",
  "cake": "c#",
  "cs.pp": "c#",
  "csx": "c#",
  "linq": "c#",
  "cpp": "c++",
  "c++": "c++",
  "cc": "c++",
  "cp": "c++",
  "cppm": "c++",
  "cxx": "c++",
  "h++": "c++",
  "hh": "c++",
  "hpp": "c++",
  "hxx": "c++",
  "inl": "c++",
  "ino": "c++",
  "ipp": "c++",
  "ixx": "c++",
  "re": "c++",
  "tcc": "c++",
  "tpp": "c++",
  "txx": "c++",
  "c-objdump": "c-objdump",
  "chs": "c2hs haskell",
  "c3": "c3",
  "cds": "cap cds",
  "cil": "cil",
  "clp": "clips",
  "cmake": "cmake",
  "cmake.in": "cmake",
  "cob": "cobol",
  "cbl": "cobol",
  "ccp": "cobol",
  "cobol": "cobol",
  "cpy": "cobol",
  "dae": "collada",
  "cql": "cql",
  "cson": "cson",
  "css": "css",
  "csv": "csv",
  "cue": "cue",
  "w": "cweb",
  "cabal": "cabal config",
  "caddyfile": "caddyfile",
  "cdc": "cadence",
  "cairo": "cairo",
  "mligo": "cameligo",
  "cj": "cangjie",
  "capnp": "cap'n proto",
  "carbon": "carbon",
  "mss": "cartocss",
  "ceylon": "ceylon",
  "chpl": "chapel",
  "ch": "charity",
  "crc32": "checksums",
  "md2": "checksums",
  "md4": "checksums",
  "md5": "checksums",
  "sha1": "checksums",
  "sha2": "checksums",
  "sha224": "checksums",
  "sha256": "checksums",
  "sha256sum": "checksums",
  "sha3": "checksums",
  "sha384": "checksums",
  "sha512": "checksums",
  "ck": "chuck",
  "circom": "circom",
  "cirru": "cirru",
  "clw": "clarion",
  "clar": "clarity",
  "asp": "classic asp",
  "icl": "clean",
  "dcl": "clean",
  "click": "click",
  "clj": "clojure",
  "boot": "clojure",
  "cl2": "clojure",
  "cljc": "clojure",
  "cljs": "clojure",
  "cljs.hl": "clojure",
  "cljscm": "clojure",
  "cljx": "clojure",
  "hic": "clojure",
  "soy": "closure templates",
  "clue": "clue",
  "conllu": "conll-u",
  "conll": "conll-u",
  "ql": "codeql",
  "qll": "codeql",
  "coffee": "coffeescript",
  "_coffee": "coffeescript",
  "cjsx": "coffeescript",
  "iced": "coffeescript",
  "cfm": "coldfusion",
  "cfml": "coldfusion",
  "cfc": "coldfusion cfc",
  "lisp": "common lisp",
  "asd": "common lisp",
  "cl": "common lisp",
  "l": "common lisp",
  "lsp": "common lisp",
  "ny": "common lisp",
  "podsl": "common lisp",
  "sexp": "common lisp",
  "cwl": "common workflow language",
  "cps": "component pascal",
  "cook": "cooklang",
  "cppobjdump": "cpp-objdump",
  "c++-objdump": "cpp-objdump",
  "c++objdump": "cpp-objdump",
  "cpp-objdump": "cpp-objdump",
  "cxx-objdump": "cpp-objdump",
  "creole": "creole",
  "cr": "crystal",
  "orc": "csound",
  "udo": "csound",
  "csd": "csound document",
  "sco": "csound score",
  "cu": "cuda",
  "cuh": "cuda",
  "curry": "curry",
  "cy": "cycript",
  "cylc": "cylc",
  "cyp": "cypher",
  "cypher": "cypher",
  "pyx": "cython",
  "pxd": "cython",
  "pxi": "cython",
  "d": "d",
  "di": "d",
  "d-objdump": "d-objdump",
  "d2": "d2",
  "com": "digital command language",
  "dm": "dm",
  "zone": "dns zone",
  "arpa": "dns zone",
  "dfy": "dafny",
  "darcspatch": "darcs patch",
  "dpatch": "darcs patch",
  "dart": "dart",
  "das": "daslang",
  "dwl": "dataweave",
  "dsc": "denizenscript",
  "dhall": "dhall",
  "diff": "diff",
  "patch": "diff",
  "x": "linker script",
  "dockerfile": "dockerfile",
  "containerfile": "dockerfile",
  "djs": "dogescript",
  "env": "dotenv",
  "dylan": "dylan",
  "dyl": "dylan",
  "intr": "dylan",
  "lid": "dylan",
  "e": "e",
  "eml": "e-mail",
  "mbox": "e-mail",
  "ebnf": "ebnf",
  "ecl": "ecl",
  "eclxml": "ecl",
  "ejs": "ejs",
  "ect": "ejs",
  "ejs.t": "ejs",
  "jst": "ejs",
  "eq": "eq",
  "sch": "scheme",
  "brd": "eagle",
  "eb": "easybuild",
  "epj": "ecere projects",
  "html": "ecmarkup",
  "edge": "edge",
  "edgeql": "edgeql",
  "esdl": "edgeql",
  "editorconfig": "editorconfig",
  "edc": "edje data collection",
  "ex": "elixir",
  "exs": "elixir",
  "elm": "elm",
  "elv": "elvish",
  "el": "emacs lisp",
  "emacs": "emacs lisp",
  "emacs.desktop": "emacs lisp",
  "em": "emberscript",
  "emberscript": "emberscript",
  "erl": "erlang",
  "app": "erlang",
  "app.src": "erlang",
  "es": "erlang",
  "escript": "erlang",
  "hrl": "erlang",
  "xrl": "erlang",
  "yrl": "erlang",
  "fs": "f#",
  "fsi": "f#",
  "fsx": "f#",
  "fst": "f*",
  "fsti": "f*",
  "flf": "figlet font",
  "fir": "firrtl",
  "fx": "flux",
  "flux": "flux",
  "factor": "factor",
  "fy": "fancy",
  "fancypack": "fancy",
  "fan": "fantom",
  "dsp": "faust",
  "fnl": "fennel",
  "f": "filebench wml",
  "fbs": "flatbuffers",
  "flix": "flix",
  "ftl": "fluent",
  "for": "forth",
  "eam.fs": "formatted",
  "fth": "forth",
  "4th": "forth",
  "forth": "forth",
  "fr": "forth",
  "frt": "forth",
  "f77": "fortran",
  "fpp": "fortran",
  "f90": "fortran free form",
  "f03": "fortran free form",
  "f08": "fortran free form",
  "f95": "fortran free form",
  "bi": "freebasic",
  "ftlh": "freemarker",
  "fut": "futhark",
  "g": "g-code",
  "cnc": "g-code",
  "gco": "g-code",
  "gcode": "g-code",
  "gaml": "gaml",
  "gms": "gams",
  "gap": "gap",
  "gd": "gap",
  "gi": "gap",
  "tst": "gap",
  "md": "gcc machine description",
  "gdb": "gdb",
  "gdbinit": "gdb",
  "gdshader": "gdshader",
  "gdshaderinc": "gdshader",
  "ged": "gedcom",
  "glsl": "glsl",
  "fp": "glsl",
  "frag": "glsl",
  "frg": "glsl",
  "fsh": "glsl",
  "fshader": "glsl",
  "geo": "glsl",
  "geom": "glsl",
  "glslf": "glsl",
  "glslv": "glsl",
  "gs": "glsl",
  "gshader": "glsl",
  "rchit": "glsl",
  "rmiss": "glsl",
  "shader": "glsl",
  "tesc": "glsl",
  "tese": "glsl",
  "vert": "glsl",
  "vrx": "glsl",
  "vs": "glsl",
  "vsh": "glsl",
  "vshader": "glsl",
  "gn": "gn",
  "gni": "gn",
  "gsc": "gsc",
  "csc": "gsc",
  "gsh": "gsc",
  "gml": "game maker language",
  "gmi": "gemini",
  "4gl": "genero 4gl",
  "per": "genero per",
  "kid": "genshi",
  "ebuild": "gentoo ebuild",
  "eclass": "gentoo eclass",
  "gbr": "gerber image",
  "cmp": "gerber image",
  "gbl": "gerber image",
  "gbo": "gerber image",
  "gbp": "gerber image",
  "gbs": "gerber image",
  "gko": "gerber image",
  "gpb": "gerber image",
  "gpt": "gerber image",
  "gtl": "gerber image",
  "gto": "gerber image",
  "gtp": "gerber image",
  "gts": "glimmer ts",
  "ncl": "ncl",
  "sol": "solidity",
  "po": "gettext catalog",
  "pot": "gettext catalog",
  "feature": "gherkin",
  "story": "gherkin",
  "gitconfig": "git config",
  "gleam": "gleam",
  "gjs": "glimmer js",
  "glf": "glyph",
  "bdf": "glyph bitmap distribution format",
  "gp": "gnuplot",
  "gnu": "gnuplot",
  "gnuplot": "gnuplot",
  "p": "gnuplot",
  "plot": "gnuplot",
  "plt": "gnuplot",
  "go": "go",
  "gohtml": "go template",
  "gotmpl": "go template",
  "html.tmpl": "go template",
  "tmpl": "go template",
  "tpl": "smarty",
  "gdnlib": "godot resource",
  "gdns": "godot resource",
  "tres": "godot resource",
  "tscn": "godot resource",
  "golo": "golo",
  "gst": "gosu",
  "gsx": "gosu",
  "vark": "gosu",
  "grace": "grace",
  "gradle": "gradle",
  "gradle.kts": "gradle kotlin dsl",
  "gf": "grammatical framework",
  "graphql": "graphql",
  "gql": "graphql",
  "graphqls": "graphql",
  "dot": "graphviz (dot)",
  "gv": "graphviz (dot)",
  "groovy": "groovy",
  "grt": "groovy",
  "gtpl": "groovy",
  "gvy": "groovy",
  "gsp": "groovy server pages",
  "cfg": "haproxy",
  "hcl": "hcl",
  "nomad": "hcl",
  "tf": "hcl",
  "tfvars": "hcl",
  "tofu": "hcl",
  "workflow": "hcl",
  "hip": "hip",
  "hlsl": "hlsl",
  "cginc": "hlsl",
  "fxh": "hlsl",
  "hlsli": "hlsl",
  "hocon": "hocon",
  "hta": "html",
  "htm": "html",
  "html.hl": "html",
  "xht": "html",
  "xhtml": "html",
  "ecr": "html+ecr",
  "html.eex": "html+eex",
  "heex": "html+eex",
  "leex": "html+eex",
  "erb": "html+erb",
  "erb.deface": "html+erb",
  "rhtml": "html+erb",
  "phtml": "html+php",
  "cshtml": "html+razor",
  "razor": "html+razor",
  "http": "http",
  "hxml": "hxml",
  "hack": "hack",
  "hhi": "hack",
  "php": "hack",
  "haml": "haml",
  "haml.deface": "haml",
  "handlebars": "handlebars",
  "hbs": "handlebars",
  "hb": "harbour",
  "ha": "hare",
  "hs": "haskell",
  "hs-boot": "haskell",
  "hsc": "haskell",
  "hx": "haxe",
  "hxsl": "haxe",
  "q": "hiveql",
  "hql": "hiveql",
  "hc": "holyc",
  "hurl": "hurl",
  "hy": "hy",
  "pro": "idl",
  "dlm": "idl",
  "ipf": "igor pro",
  "ini": "ini",
  "cnf": "ini",
  "dof": "ini",
  "frm": "vba",
  "lektorproject": "ini",
  "prefs": "ini",
  "properties": "ini",
  "url": "ini",
  "irclog": "irc log",
  "weechatlog": "irc log",
  "ispc": "ispc",
  "idr": "idris",
  "lidr": "idris",
  "gitignore": "ignore list",
  "ijm": "imagej macro",
  "imba": "imba",
  "ni": "inform 7",
  "i7x": "inform 7",
  "ink": "ink",
  "iss": "inno setup",
  "isl": "inno setup",
  "io": "io",
  "ik": "ioke",
  "thy": "isabelle",
  "ijs": "j",
  "jcl": "jcl",
  "flex": "jflex",
  "jflex": "jflex",
  "json": "json",
  "4DForm": "json",
  "4DProject": "json",
  "avsc": "json",
  "geojson": "json",
  "gltf": "json",
  "har": "json",
  "ice": "slice",
  "JSON-tmLanguage": "json",
  "json.example": "json",
  "jsonl": "json",
  "mcmeta": "json",
  "sarif": "json",
  "tact": "tact",
  "tfstate": "json",
  "tfstate.backup": "json",
  "topojson": "json",
  "webapp": "json",
  "webmanifest": "json",
  "yy": "yacc",
  "yyp": "json",
  "jsonc": "json with comments",
  "code-snippets": "json with comments",
  "code-workspace": "json with comments",
  "sublime-build": "json with comments",
  "sublime-color-scheme": "json with comments",
  "sublime-commands": "json with comments",
  "sublime-completions": "json with comments",
  "sublime-keymap": "json with comments",
  "sublime-macro": "json with comments",
  "sublime-menu": "json with comments",
  "sublime-mousemap": "json with comments",
  "sublime-project": "json with comments",
  "sublime-settings": "json with comments",
  "sublime-theme": "json with comments",
  "sublime-workspace": "json with comments",
  "sublime_metrics": "json with comments",
  "sublime_session": "json with comments",
  "tsconfig.json": "json with comments",
  "json5": "json5",
  "jsonld": "jsonld",
  "jq": "jsoniq",
  "jac": "jac",
  "jai": "jai",
  "janet": "janet",
  "j": "jasmin",
  "java": "java",
  "jav": "java",
  "jsh": "java",
  "jsp": "java server pages",
  "tag": "java server pages",
  "jte": "java template engine",
  "js": "javascript",
  "_js": "javascript",
  "bones": "javascript",
  "cjs": "javascript",
  "es6": "javascript",
  "jake": "javascript",
  "javascript": "javascript",
  "jsb": "javascript",
  "jscad": "javascript",
  "jsfl": "javascript",
  "jslib": "javascript",
  "jsm": "javascript",
  "jspre": "javascript",
  "jss": "javascript",
  "jsx": "javascript",
  "mjs": "javascript",
  "njs": "javascript",
  "pac": "javascript",
  "sjs": "javascript",
  "ssjs": "javascript",
  "xsjs": "javascript",
  "xsjslib": "javascript",
  "js.erb": "javascript+erb",
  "snap": "jest snapshot",
  "mps": "jetbrains mps",
  "mpl": "jetbrains mps",
  "msd": "jetbrains mps",
  "jinja": "jinja",
  "j2": "jinja",
  "jinja2": "jinja",
  "jison": "jison",
  "jisonlex": "jison lex",
  "ol": "jolie",
  "iol": "jolie",
  "jsonnet": "jsonnet",
  "libsonnet": "jsonnet",
  "jl": "julia",
  "ipynb": "jupyter notebook",
  "just": "just",
  "k": "kcl",
  "kdl": "kdl",
  "krl": "krl",
  "ksy": "kaitai struct",
  "kak": "kakounescript",
  "ks": "kerboscript",
  "kicad_pcb": "kicad layout",
  "kicad_mod": "kicad layout",
  "kicad_wks": "kicad layout",
  "kicad_sch": "kicad schematic",
  "kicad_sym": "kicad schematic",
  "kit": "kit",
  "kk": "koka",
  "kt": "kotlin",
  "ktm": "kotlin",
  "kts": "kotlin",
  "csl": "kusto",
  "kql": "kusto",
  "lfe": "lfe",
  "ll": "llvm",
  "lol": "lolcode",
  "lsl": "lsl",
  "lslp": "lsl",
  "lvproj": "labview",
  "lvclass": "labview",
  "lvlib": "labview",
  "langium": "langium",
  "lark": "lark",
  "lasso": "lasso",
  "las": "lasso",
  "lasso8": "lasso",
  "lasso9": "lasso",
  "latte": "latte",
  "lean": "lean",
  "hlean": "lean",
  "leo": "leo",
  "less": "less",
  "lex": "lex",
  "ligo": "ligolang",
  "ly": "lilypond",
  "ily": "lilypond",
  "m": "limbo",
  "ld": "linker script",
  "lds": "linker script",
  "liquid": "liquid",
  "liq": "liquidsoap",
  "lagda": "literate agda",
  "litcoffee": "literate coffeescript",
  "coffee.md": "literate coffeescript",
  "lhs": "literate haskell",
  "livecodescript": "livecode script",
  "ls": "livescript",
  "_ls": "livescript",
  "xm": "logos",
  "xi": "logos",
  "lgt": "logtalk",
  "logtalk": "logtalk",
  "lkml": "lookml",
  "lookml": "lookml",
  "lua": "lua",
  "fcgi": "lua",
  "nse": "lua",
  "p8": "lua",
  "pd_lua": "lua",
  "rbxs": "lua",
  "rockspec": "lua",
  "wlua": "lua",
  "luau": "luau",
  "mumps": "m",
  "m3u": "m3u",
  "m3u8": "m3u",
  "m4": "m4",
  "mc": "m4",
  "matlab": "matlab",
  "ms": "maxscript",
  "mcr": "maxscript",
  "mdx": "mdx",
  "mlir": "mlir",
  "mq4": "mql4",
  "mqh": "mql4",
  "mq5": "mql5",
  "mtml": "mtml",
  "muf": "muf",
  "m2": "macaulay2",
  "mak": "makefile",
  "make": "makefile",
  "makefile": "makefile",
  "mk": "makefile",
  "mkfile": "makefile",
  "mako": "mako",
  "mao": "mako",
  "livemd": "markdown",
  "markdown": "markdown",
  "mdown": "markdown",
  "mdwn": "markdown",
  "mkd": "markdown",
  "mkdn": "markdown",
  "mkdown": "markdown",
  "ronn": "markdown",
  "scd": "supercollider",
  "workbook": "markdown",
  "marko": "marko",
  "mask": "mask",
  "maxpat": "max",
  "maxhelp": "max",
  "maxproj": "max",
  "mxt": "max",
  "pat": "max",
  "metta": "metta",
  "moo": "mercury",
  "mmd": "mermaid",
  "mermaid": "mermaid",
  "metal": "metal",
  "sln": "microsoft visual studio solution",
  "minid": "minid",
  "yaml": "miniyaml",
  "yml": "miniyaml",
  "mzn": "minizinc",
  "dzn": "minizinc data",
  "mint": "mint",
  "druby": "mirah",
  "duby": "mirah",
  "mirah": "mirah",
  "mo": "modelica",
  "i3": "modula-3",
  "ig": "modula-3",
  "m3": "modula-3",
  "mg": "modula-3",
  "mms": "module management system",
  "mmk": "module management system",
  "mojo": "mojo",
  "monkey": "monkey",
  "monkey2": "monkey",
  "mbt": "moonbit",
  "moon": "moonscript",
  "x68": "motorola 68k assembly",
  "move": "move",
  "muse": "muse",
  "mustache": "mustache",
  "myt": "myghty",
  "nasl": "nasl",
  "neon": "neon",
  "nl": "newlisp",
  "nsi": "nsis",
  "nsh": "nsis",
  "nss": "nwscript",
  "ne": "nearley",
  "nearley": "nearley",
  "n": "nemerle",
  "axs": "netlinx",
  "axi": "netlinx",
  "axs.erb": "netlinx+erb",
  "axi.erb": "netlinx+erb",
  "nlogo": "netlogo",
  "nf": "nextflow",
  "nginx": "nginx",
  "nginxconf": "nginx",
  "nim": "nim",
  "nim.cfg": "nim",
  "nimble": "nim",
  "nimrod": "nim",
  "nims": "nim",
  "ninja": "ninja",
  "nit": "nit",
  "nix": "nix",
  "nr": "noir",
  "nu": "nu",
  "numpy": "numpy",
  "numpyw": "numpy",
  "numsc": "numpy",
  "njk": "nunjucks",
  "ml": "ocaml",
  "eliom": "ocaml",
  "eliomi": "ocaml",
  "ml4": "ocaml",
  "mli": "ocaml",
  "mll": "ocaml",
  "mly": "ocaml",
  "msg": "omnet++ msg",
  "ned": "omnet++ ned",
  "ob2": "oberon",
  "objdump": "objdump",
  "odin": "odin",
  "mm": "objective-c++",
  "sj": "objective-j",
  "omgrofl": "omgrofl",
  "opa": "opa",
  "opal": "opal",
  "rego": "open policy agent",
  "opencl": "opencl",
  "qasm": "openqasm",
  "scad": "openscad",
  "plist": "openstep property list",
  "glyphs": "openstep property list",
  "fea": "opentype feature file",
  "org": "org",
  "overpassql": "overpassql",
  "ox": "ox",
  "oxh": "ox",
  "oxo": "ox",
  "oxygene": "oxygene",
  "oz": "oz",
  "p4": "p4",
  "pddl": "pddl",
  "pegjs": "peg.js",
  "peggy": "peg.js",
  "aw": "php",
  "ctp": "php",
  "php3": "php",
  "php4": "php",
  "php5": "php",
  "phps": "php",
  "phpt": "php",
  "pls": "plsql",
  "bdy": "plsql",
  "ddl": "plsql",
  "fnc": "plsql",
  "pck": "plsql",
  "pkb": "plsql",
  "pks": "plsql",
  "plb": "plsql",
  "plsql": "plsql",
  "prc": "plsql",
  "spc": "plsql",
  "sql": "plsql",
  "tpb": "plsql",
  "tps": "plsql",
  "trg": "plsql",
  "vw": "plsql",
  "pgsql": "plpgsql",
  "pov": "pov-ray sdl",
  "pact": "pact",
  "pan": "pan",
  "psc": "papyrus",
  "parrot": "parrot",
  "pasm": "parrot assembly",
  "pir": "parrot internal representation",
  "pas": "pascal",
  "dfm": "pascal",
  "dpr": "pascal",
  "lpr": "pascal",
  "pascal": "pascal",
  "pp": "pascal",
  "pwn": "pawn",
  "sma": "pawn",
  "pep": "pep8",
  "pl": "perl",
  "cgi": "perl",
  "perl": "perl",
  "ph": "perl",
  "plx": "perl",
  "pm": "perl",
  "psgi": "perl",
  "t": "perl",
  "pic": "pic",
  "chem": "pic",
  "pkl": "pkl",
  "pig": "piglatin",
  "pike": "pike",
  "pmod": "pike",
  "puml": "plantuml",
  "iuml": "plantuml",
  "plantuml": "plantuml",
  "pod": "pod",
  "pod6": "pod 6",
  "pogo": "pogoscript",
  "polar": "polar",
  "pony": "pony",
  "por": "portugol",
  "pcss": "postcss",
  "postcss": "postcss",
  "ps": "postscript",
  "eps": "postscript",
  "epsi": "postscript",
  "pfa": "postscript",
  "pbt": "powerbuilder",
  "sra": "powerbuilder",
  "sru": "powerbuilder",
  "srw": "powerbuilder",
  "ps1": "powershell",
  "psd1": "powershell",
  "psm1": "powershell",
  "praat": "praat",
  "prisma": "prisma",
  "pde": "processing",
  "prolog": "prolog",
  "yap": "prolog",
  "pml": "promela",
  "spin": "propeller spin",
  "proto": "protocol buffer",
  "textproto": "protocol buffer text format",
  "pbtxt": "protocol buffer text format",
  "txtpb": "protocol buffer text format",
  "pub": "public key",
  "jade": "pug",
  "pug": "pug",
  "pd": "pure data",
  "pb": "purebasic",
  "pbi": "purebasic",
  "purs": "purescript",
  "arr": "pyret",
  "py": "python",
  "gyp": "python",
  "gypi": "python",
  "lmi": "python",
  "py3": "python",
  "pyde": "python",
  "pyi": "python",
  "pyp": "python",
  "pyt": "python",
  "pyw": "python",
  "rpy": "python",
  "spec": "python",
  "tac": "python",
  "wsgi": "python",
  "xpy": "python",
  "pytb": "python traceback",
  "qs": "q#",
  "qml": "qml",
  "qbs": "qml",
  "pri": "qmake",
  "qc": "quakec",
  "r": "r",
  "rd": "r",
  "rsx": "r",
  "raml": "raml",
  "rascript": "rascript",
  "rbs": "rbs",
  "rdoc": "rdoc",
  "rbbas": "realbasic",
  "rbfrm": "realbasic",
  "rbmnu": "realbasic",
  "rbres": "realbasic",
  "rbtbar": "realbasic",
  "rbuistate": "realbasic",
  "rexx": "rexx",
  "pprx": "rexx",
  "rex": "rexx",
  "qmd": "rmarkdown",
  "rmd": "rmarkdown",
  "ron": "ron",
  "action": "ros interface",
  "srv": "ros interface",
  "rpgle": "rpgle",
  "sqlrpgle": "rpgle",
  "rnh": "runoff",
  "rno": "runoff",
  "rkt": "racket",
  "rktd": "racket",
  "rktl": "racket",
  "scrbl": "racket",
  "rl": "ragel",
  "6pl": "raku",
  "6pm": "raku",
  "nqp": "raku",
  "p6": "raku",
  "p6l": "raku",
  "p6m": "raku",
  "pl6": "raku",
  "pm6": "raku",
  "raku": "raku",
  "rakumod": "raku",
  "rsc": "rascal",
  "raw": "raw token data",
  "res": "rescript",
  "resi": "rescript",
  "rei": "reason",
  "religo": "reasonligo",
  "reb": "rebol",
  "r2": "rebol",
  "r3": "rebol",
  "rebol": "rebol",
  "red": "red",
  "reds": "red",
  "cw": "redcode",
  "regexp": "regular expression",
  "regex": "regular expression",
  "rs": "renderscript",
  "rsh": "renderscript",
  "rtf": "rich text format",
  "ring": "ring",
  "riot": "riot",
  "robot": "robotframework",
  "resource": "robotframework",
  "roc": "roc",
  "v": "rocq prover",
  "coq": "rocq prover",
  "roff": "roff",
  "1in": "roff",
  "1m": "roff",
  "1x": "roff",
  "3in": "roff",
  "3m": "roff",
  "3p": "roff",
  "3pm": "roff",
  "3qt": "roff",
  "3x": "roff",
  "man": "roff",
  "mdoc": "roff",
  "me": "roff",
  "tmac": "roff",
  "rg": "rouge",
  "rb": "ruby",
  "builder": "ruby",
  "eye": "ruby",
  "gemspec": "ruby",
  "god": "ruby",
  "jbuilder": "ruby",
  "mspec": "ruby",
  "pluginspec": "ruby",
  "podspec": "ruby",
  "prawn": "ruby",
  "rabl": "ruby",
  "rake": "ruby",
  "rbi": "ruby",
  "rbuild": "ruby",
  "rbw": "ruby",
  "rbx": "ruby",
  "ru": "ruby",
  "ruby": "ruby",
  "thor": "ruby",
  "watchr": "ruby",
  "rs.in": "rust",
  "sas": "sas",
  "scss": "scss",
  "te": "selinux policy",
  "smt2": "smt",
  "smt": "smt",
  "z3": "smt",
  "sparql": "sparql",
  "rq": "sparql",
  "sqf": "sqf",
  "hqf": "sqf",
  "mysql": "sql",
  "tab": "sql",
  "udf": "sql",
  "viw": "sql",
  "db2": "sqlpl",
  "srt": "srecode template",
  "star": "starlark",
  "stl": "stl",
  "ston": "ston",
  "svg": "svg",
  "swg": "swig",
  "swig": "swig",
  "sage": "sage",
  "sagews": "sage",
  "sail": "sail",
  "sls": "saltstack",
  "sass": "sass",
  "scala": "scala",
  "kojo": "scala",
  "sbt": "scala",
  "sc": "scala",
  "scaml": "scaml",
  "scenic": "scenic",
  "scm": "scheme",
  "sld": "scheme",
  "sps": "scheme",
  "ss": "scheme",
  "sci": "scilab",
  "sce": "scilab",
  "self": "self",
  "sh": "shell",
  "bash": "shell",
  "bats": "shell",
  "command": "shell",
  "ksh": "shell",
  "sbatch": "shell",
  "sh.in": "shell",
  "slurm": "shell",
  "tmux": "shell",
  "tool": "shell",
  "zsh": "shell",
  "zsh-theme": "shell",
  "sh-session": "shellsession",
  "shen": "shen",
  "sieve": "sieve",
  "sfv": "simple file verification",
  "slang": "slang",
  "sl": "slash",
  "slim": "slim",
  "slint": "slint",
  "cocci": "smpl",
  "smali": "smali",
  "st": "smalltalk",
  "smithy": "smithy",
  "smk": "snakemake",
  "snakefile": "snakemake",
  "sp": "sourcepawn",
  "sfd": "spline font database",
  "nut": "squirrel",
  "stan": "stan",
  "fun": "standard ml",
  "sig": "standard ml",
  "sml": "standard ml",
  "bzl": "starlark",
  "do": "stata",
  "ado": "stata",
  "doh": "stata",
  "ihlp": "stata",
  "mata": "stata",
  "matah": "stata",
  "sthlp": "stata",
  "styl": "stylus",
  "sss": "sugarss",
  "surql": "surrealql",
  "svx": "mdsvex",
  "svelte": "svelte",
  "sw": "sway",
  "rnw": "sweave",
  "swift": "swift",
  "sv": "systemverilog",
  "svh": "systemverilog",
  "vh": "systemverilog",
  "8xp": "ti program",
  "8xp.txt": "ti program",
  "tlv": "tl-verilog",
  "tla": "tla",
  "tmdl": "tmdl",
  "toml": "toml",
  "toml.example": "toml",
  "tsp": "typespec",
  "tsv": "tsv",
  "vcf": "tsv",
  "tsx": "tsx",
  "txl": "txl",
  "talon": "talon",
  "tcl": "tcl",
  "adp": "tcl",
  "sdc": "tcl",
  "tcl.in": "tcl",
  "tm": "tcl",
  "xdc": "tcl",
  "tcsh": "tcsh",
  "csh": "tcsh",
  "tex": "tex",
  "aux": "tex",
  "bbx": "tex",
  "cbx": "tex",
  "dtx": "tex",
  "ins": "tex",
  "lbx": "tex",
  "ltx": "tex",
  "mkii": "tex",
  "mkiv": "tex",
  "mkvi": "tex",
  "sty": "tex",
  "toc": "tex",
  "tea": "tea",
  "tl": "teal",
  "tftpl": "terraform template",
  "texinfo": "texinfo",
  "texi": "texinfo",
  "txi": "texinfo",
  "nb": "wolfram language",
  "no": "text",
  "TextGrid": "textgrid",
  "textile": "textile",
  "thrift": "thrift",
  "toit": "toit",
  "tu": "turing",
  "ttl": "turtle",
  "twig": "twig",
  "ts": "typescript",
  "cts": "typescript",
  "mts": "typescript",
  "typ": "typst",
  "upc": "unified parallel c",
  "anim": "unity3d asset",
  "asset": "unity3d asset",
  "mat": "unity3d asset",
  "meta": "unity3d asset",
  "prefab": "unity3d asset",
  "unity": "unity3d asset",
  "uno": "uno",
  "uc": "unrealscript",
  "uplc": "untyped plutus core",
  "ur": "urweb",
  "urs": "urweb",
  "vba": "vba",
  "vbs": "vbscript",
  "vcl": "vcl",
  "vhdl": "vhdl",
  "vhd": "vhdl",
  "vhf": "vhdl",
  "vhi": "vhdl",
  "vho": "vhdl",
  "vhs": "vhdl",
  "vht": "vhdl",
  "vhw": "vhdl",
  "vala": "vala",
  "vapi": "vala",
  "vdf": "valve data format",
  "vtl": "velocity template language",
  "vto": "vento",
  "veo": "verilog",
  "vim": "vim script",
  "vimrc": "vim script",
  "vmb": "vim script",
  "snip": "vim snippet",
  "snippet": "vim snippet",
  "snippets": "vim snippet",
  "vb": "visual basic .net",
  "vbhtml": "visual basic .net",
  "ctl": "visual basic 6.0",
  "Dsr": "visual basic 6.0",
  "volt": "volt",
  "vue": "vue",
  "vy": "vyper",
  "wdl": "wdl",
  "wgsl": "wgsl",
  "mtl": "wavefront material",
  "obj": "wavefront object",
  "owl": "web ontology language",
  "wast": "webassembly",
  "wat": "webassembly",
  "wit": "webassembly interface type",
  "webidl": "webidl",
  "vtt": "webvtt",
  "whiley": "whiley",
  "mediawiki": "wikitext",
  "wiki": "wikitext",
  "wikitext": "wikitext",
  "reg": "windows registry entries",
  "ws": "witcher script",
  "mathematica": "wolfram language",
  "cdf": "wolfram language",
  "ma": "wolfram language",
  "mt": "wolfram language",
  "nbp": "wolfram language",
  "wl": "wolfram language",
  "wls": "wolfram language",
  "wlt": "wolfram language",
  "wlk": "wollok",
  "wren": "wren",
  "xbm": "x bitmap",
  "xpm": "x pixmap",
  "x10": "x10",
  "xc": "xc",
  "xml": "xml",
  "adml": "xml",
  "admx": "xml",
  "ant": "xml",
  "axaml": "xml",
  "axml": "xml",
  "builds": "xml",
  "ccproj": "xml",
  "ccxml": "xml",
  "clixml": "xml",
  "cproject": "xml",
  "cscfg": "xml",
  "csdef": "xml",
  "csproj": "xml",
  "ct": "xml",
  "depproj": "xml",
  "dita": "xml",
  "ditamap": "xml",
  "ditaval": "xml",
  "dll.config": "xml",
  "dotsettings": "xml",
  "filters": "xml",
  "fsproj": "xml",
  "fxml": "xml",
  "glade": "xml",
  "gmx": "xml",
  "gpx": "xml",
  "grxml": "xml",
  "hzp": "xml",
  "icls": "xml",
  "iml": "xml",
  "ivy": "xml",
  "jelly": "xml",
  "jsproj": "xml",
  "kml": "xml",
  "launch": "xml",
  "mdpolicy": "xml",
  "mjml": "xml",
  "mxml": "xml",
  "natvis": "xml",
  "ndproj": "xml",
  "nproj": "xml",
  "nuspec": "xml",
  "odd": "xml",
  "osm": "xml",
  "pkgproj": "xml",
  "proj": "xml",
  "props": "xml",
  "ps1xml": "xml",
  "psc1": "xml",
  "pt": "xml",
  "pubxml": "xml",
  "qhelp": "xml",
  "rdf": "xml",
  "resx": "xml",
  "rss": "xml",
  "scxml": "xml",
  "sfproj": "xml",
  "shproj": "xml",
  "slnx": "xml",
  "srdf": "xml",
  "storyboard": "xml",
  "sublime-snippet": "xml",
  "targets": "xml",
  "tml": "xml",
  "ui": "xml",
  "urdf": "xml",
  "ux": "xml",
  "vbproj": "xml",
  "vcxproj": "xml",
  "vsixmanifest": "xml",
  "vssettings": "xml",
  "vstemplate": "xml",
  "vxml": "xml",
  "wixproj": "xml",
  "wsdl": "xml",
  "wsf": "xml",
  "wxi": "xml",
  "wxl": "xml",
  "wxs": "xml",
  "x3d": "xml",
  "xacro": "xml",
  "xaml": "xml",
  "xib": "xml",
  "xlf": "xml",
  "xliff": "xml",
  "xmi": "xml",
  "xml.dist": "xml",
  "xmp": "xml",
  "xproj": "xml",
  "xsd": "xml",
  "xspec": "xml",
  "xul": "xml",
  "zcml": "xml",
  "stTheme": "xml property list",
  "tmCommand": "xml property list",
  "tmLanguage": "xml property list",
  "tmPreferences": "xml property list",
  "tmSnippet": "xml property list",
  "tmTheme": "xml property list",
  "xsp-config": "xpages",
  "xsp.metadata": "xpages",
  "xpl": "xproc",
  "xproc": "xproc",
  "xquery": "xquery",
  "xq": "xquery",
  "xql": "xquery",
  "xqm": "xquery",
  "xqy": "xquery",
  "xs": "xs",
  "xslt": "xslt",
  "xsl": "xslt",
  "xojo_code": "xojo",
  "xojo_menu": "xojo",
  "xojo_report": "xojo",
  "xojo_script": "xojo",
  "xojo_toolbar": "xojo",
  "xojo_window": "xojo",
  "xsh": "xonsh",
  "xtend": "xtend",
  "mir": "yaml",
  "reek": "yaml",
  "rviz": "yaml",
  "sublime-syntax": "yaml",
  "syntax": "yaml",
  "yaml-tmlanguage": "yaml",
  "yaml.sed": "yaml",
  "yml.mysql": "yaml",
  "yang": "yang",
  "yar": "yara",
  "yara": "yara",
  "yasnippet": "yasnippet",
  "y": "yacc",
  "yacc": "yacc",
  "yul": "yul",
  "zap": "zap",
  "xzap": "zap",
  "zil": "zil",
  "mud": "zil",
  "zeek": "zeek",
  "bro": "zeek",
  "zs": "zenscript",
  "zep": "zephir",
  "zig": "zig",
  "zig.zon": "zig",
  "zimpl": "zimpl",
  "zmpl": "zimpl",
  "zpl": "zimpl",
  "zmodel": "zmodel",
  "desktop": "desktop",
  "desktop.in": "desktop",
  "service": "desktop",
  "dircolors": "dircolors",
  "ec": "ec",
  "eh": "ec",
  "edn": "edn",
  "fish": "fish",
  "hoon": "hoon",
  "ics": "icalendar",
  "ical": "icalendar",
  "kv": "kvlang",
  "mrc": "mirc script",
  "mcfunction": "mcfunction",
  "mu": "mupad",
  "nanorc": "nanorc",
  "nc": "nesc",
  "ooc": "ooc",
  "rst": "restructuredtext",
  "rest": "restructuredtext",
  "rest.txt": "restructuredtext",
  "rst.txt": "restructuredtext",
  "sed": "sed",
  "templ": "templ",
  "wisp": "wisp",
  "prg": "xbase",
  "prw": "xbase"
};
// --- AUTO-GENERATED LANGUAGE MAP END ---

function inferLanguage(path: string): string {
  const normalized = normalizeExtractorPath(path);
  const base = normalized.split("/").pop() ?? normalized;
  const extension = base.includes(".") ? base.split(".").pop() ?? "" : "";
  return LANGUAGE_BY_EXTENSION[extension] ?? "unknown";
}

export function buildRepoManifest(
  repositoryName: string,
  files: InventoryInputFile[],
): RepoManifest {
  return {
    repository: {
      name: repositoryName,
    },
    generated_at: new Date().toISOString(),
    files: files.map((file) => ({
      path: file.path,
      language: inferLanguage(file.path),
      size_bytes: file.size_bytes,
      hash: file.hash,
    })),
  };
}
