// N3 (A2 re-review F6-1): the accepted-results pair is ONE logical record
// written as two files. `writeAcceptedResults` used to write the RENDER
// (host-accepted-results.json) first and the LEDGER second, so a throw between
// them left the render naming an entry the ledger — the loader's source of
// truth, and what dedupes bindings — had never recorded. This pins the
// truth-first ORDER mechanically: wrap the shared JSON writer, fail the SECOND
// write (the render) of the accept, and prove the loader-visible state stays
// consistent — the entry exists exactly once in the ledger, the next ingest
// does NOT re-accept it, and the stale render is regenerated by the pair's next
// successful write.
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

// Fail exactly ONE render write when armed, delegating everything else.
const harness = vi.hoisted(() => ({ failNextRenderWrite: false }));

vi.mock("audit-tools/shared", async (importOriginal) => {
  const actual =
    await importOriginal<typeof import("audit-tools/shared")>();
  return {
    ...actual,
    writeJsonFile: async (path: string, value: unknown): Promise<void> => {
      if (
        harness.failNextRenderWrite &&
        path.endsWith("host-accepted-results.json")
      ) {
        harness.failNextRenderWrite = false;
        throw new Error("simulated crash after the ledger write");
      }
      return actual.writeJsonFile(path, value);
    },
  };
});

const cleanupRoots: string[] = [];

afterEach(async () => {
  await Promise.all(
    cleanupRoots.splice(0).map((path) => rm(path, { recursive: true, force: true })),
  );
});

const RUN_ID = "host-run-pair-order";

const AUDIT_TASK = {
  task_id: "audit-task-a",
  unit_id: "unit-audit-task-a",
  pass_id: "pass:correctness",
  lens: "correctness",
  file_paths: ["src/a.ts"],
  rationale: "Review src/a.ts",
};

async function setup() {
  const { prepareAuditHostHandoff } = await import(
    "../../src/audit/cli/dispatch/hostHandoff.js"
  );
  const root = await mkdtemp(join(tmpdir(), "audit-pair-order-"));
  cleanupRoots.push(root);
  const artifactsDir = join(root, ".audit-tools", "audit");
  await mkdir(join(root, "src"), { recursive: true });
  await writeFile(join(root, "src", "a.ts"), "one\ntwo\n", "utf8");
  const task = {
    ...AUDIT_TASK,
    priority: "medium",
    complexity: "standard",
    risk: "medium",
    token_estimate: 1200,
    file_line_counts: { "src/a.ts": 2 },
  };
  const prepared = await prepareAuditHostHandoff({
    root,
    artifactsDir,
    runId: RUN_ID,
    tasks: [task],
  });
  const item = prepared.workload.work_items.find(
    (entry) => entry.id === AUDIT_TASK.task_id,
  );
  if (!item) throw new Error("prepare did not publish the work item");
  const resultPath = join(root, item.result_path);
  await mkdir(join(resultPath, ".."), { recursive: true });
  await writeFile(
    resultPath,
    JSON.stringify({
      contract_version: "audit-host-result/v1alpha1",
      result_id: `result-${item.id}`,
      run_id: RUN_ID,
      work_item_id: item.id,
      prompt_sha256: item.prompt.sha256,
      file_coverage: [{ path: "src/a.ts", reviewed_lines: 2, total_lines: 2 }],
      findings: [],
    }),
    "utf8",
  );

  const ledgerPath = () =>
    join(artifactsDir, "runs", RUN_ID, "host-accepted-results-ledger.json");
  const renderPath = () =>
    join(artifactsDir, "runs", RUN_ID, "host-accepted-results.json");
  const readLedgerIds = async (): Promise<string[]> => {
    const ledger = JSON.parse(await readFile(ledgerPath(), "utf8")) as {
      entries: { work_item_id: string }[];
    };
    return ledger.entries.map((entry) => entry.work_item_id);
  };

  const ingest = async () => {
    const { ingestAuditHostResults } = await import(
      "../../src/audit/cli/dispatch/hostHandoff.js"
    );
    return ingestAuditHostResults({
      root,
      artifactsDir,
      runId: RUN_ID,
      auditTasks: [{ ...AUDIT_TASK }],
      lineIndex: { "src/a.ts": 2 },
    });
  };

  return { root, artifactsDir, ingest, ledgerPath, renderPath, readLedgerIds };
}

describe("contract:accepted-pair-writes-the-ledger-first", () => {
  it("a crash between the two writes cannot make the render outrun the ledger", async () => {
    const ctx = await setup();

    // Arm: the accept's LEDGER write lands, the RENDER write crashes.
    harness.failNextRenderWrite = true;
    await expect(ctx.ingest()).rejects.toThrow(
      /simulated crash after the ledger write/u,
    );

    // Loader-visible truth: the ledger recorded the entry EXACTLY once.
    expect(await ctx.readLedgerIds()).toEqual([AUDIT_TASK.task_id]);

    // The next ingest derives from the LEDGER: the binding is already accepted,
    // so nothing is re-accepted (no duplicate), yet the accepted RESULTS view
    // still carries the entry exactly once.
    const next = await ctx.ingest();
    expect(next.accepted_count).toBe(0);
    expect(next.accepted_results).toHaveLength(1);
    expect(next.completed_work_item_ids).toEqual([AUDIT_TASK.task_id]);
    expect(await ctx.readLedgerIds()).toEqual([AUDIT_TASK.task_id]);

    // The stale render is repaired by the pair's NEXT SUCCESSFUL write — here,
    // the operator drop rewriting both files together.
    const { dropAcceptedResults } = await import(
      "../../src/audit/cli/dispatch/hostHandoff.js"
    );
    await dropAcceptedResults({
      root: ctx.root,
      artifactsDir: ctx.artifactsDir,
      runId: RUN_ID,
      all: true,
    });
    const render = JSON.parse(await readFile(ctx.renderPath(), "utf8")) as unknown[];
    expect(render).toEqual([]);
    expect(await ctx.readLedgerIds()).toEqual([]);
  });
});
