export const ARTIFACT_DEPENDENCY_MAP: Record<string, string[]> = {
  "tooling_manifest.json": [
    "repo_manifest.json",
  ],
  "repo_manifest.json": [
    "file_disposition.json",
    "unit_manifest.json",
    "surface_manifest.json",
    "graph_bundle.json",
    "critical_flows.json",
    "risk_register.json",
    "coverage_matrix.json",
    "flow_coverage.json",
    "audit_tasks.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "requeue_tasks.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "file_disposition.json": [
    "unit_manifest.json",
    "surface_manifest.json",
    "graph_bundle.json",
    "critical_flows.json",
    "risk_register.json",
    "coverage_matrix.json",
    "flow_coverage.json",
    "audit_tasks.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "requeue_tasks.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "unit_manifest.json": [
    "risk_register.json",
    "design_assessment.json",
    "coverage_matrix.json",
    "audit_tasks.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "runtime_validation_tasks.json",
    "requeue_tasks.json",
    "audit-report.md",
  ],
  "surface_manifest.json": [
    "critical_flows.json",
    "risk_register.json",
    "runtime_validation_tasks.json",
    "audit-report.md",
  ],
  "critical_flows.json": [
    "flow_coverage.json",
    "risk_register.json",
    "design_assessment.json",
    "audit_tasks.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "requeue_tasks.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "design_assessment.json": [
    "audit-report.md",
  ],
  "external_analyzer_results.json": [
    "coverage_matrix.json",
    "flow_coverage.json",
    "audit_tasks.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "requeue_tasks.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "syntax_resolution_status.json": [
    "audit-report.md",
  ],
  "audit_results.jsonl": [
    "coverage_matrix.json",
    "flow_coverage.json",
    "requeue_tasks.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "coverage_matrix.json": [
    "flow_coverage.json",
    "audit_plan_metrics.json",
    "review_packets.json",
    "requeue_tasks.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "flow_coverage.json": [
    "requeue_tasks.json",
    "runtime_validation_tasks.json",
    "runtime_validation_report.json",
    "audit-report.md",
  ],
  "audit_tasks.json": [
    "audit_plan_metrics.json",
    "review_packets.json",
  ],
  "audit_plan_metrics.json": [],
  "review_packets.json": [],
  "runtime_validation_report.json": [
    "audit-report.md",
  ],
  // The canonical machine contract is co-produced with audit-report.md by the
  // synthesis executor. The optional narrative pass tracks its revision: a fresh
  // (re-synthesized) audit-findings.json re-stales the narrative marker so the
  // themes/executive-summary/top-risks regenerate. See spec/dependency-map.md.
  "audit-findings.json": [
    "synthesis-narrative.json",
  ],
};
